export enum BuildingDataEnum {
  ocupacao = 'ocupacao',
  testada = 'testada',
  posicao1 = 'posicao1',
  pedologia = 'pedologia',
  topografia = 'topografia',
  caracterizacao = 'caracterizacao',
  ultilizacao = 'ultilizacao',
  sit_const_und = 'sit_const_und',
  estrutura = 'estrutura',
  parede = 'parede',
  cobertura = 'cobertura',
  rev_externo = 'rev_externo',
  posicao2 = 'posicao2',
  alinhamento = 'alinhamento',
  conservacao = 'conservacao',
  uso_do_imovel = 'uso_do_imovel',
  piso = 'piso',
  forro = 'forro',
  rev_interno = 'rev_interno'
}
