import { tableSchema } from '@nozbe/watermelondb'

export const inspectionSheetSchema = tableSchema({
  name: 'inspection_sheets',
  columns: [
    { name: 'processosId', type: 'number' },
    { name: 'protocolo', type: 'string' },
    { name: 'dataFolha', type: 'string' },
    { name: 'logradouro', type: 'string' },
    { name: 'insc_cadastral', type: 'string' },
    { name: 'nPredial', type: 'string' },
    { name: 'ocupacao', type: 'string' },
    { name: 'testada', type: 'string' },
    { name: 'posicao1', type: 'string' },
    { name: 'pedologia', type: 'string' },
    { name: 'topografia', type: 'string' },
    { name: 'caracterizacao', type: 'string' },
    { name: 'ultilizacao', type: 'string' },
    { name: 'sit_const_und', type: 'string' },
    { name: 'estrutura', type: 'string' },
    { name: 'parede', type: 'string' },
    { name: 'cobertura', type: 'string' },
    { name: 'rev_externo', type: 'string' },
    { name: 'posicao2', type: 'string' },
    { name: 'alinhamento', type: 'string' },
    { name: 'conservacao', type: 'string' },
    { name: 'uso_do_imovel', type: 'string' },
    { name: 'area_construida', type: 'string' },
    { name: 'piso', type: 'string' },
    { name: 'forro', type: 'string' },
    { name: 'rev_interno', type: 'string' },
    { name: 'posse', type: 'string' },
    { name: 'observacao', type: 'string', isOptional: true },
    { name: 'vistoridorEmail', type: 'string' },
    { name: 'condominio', type: 'boolean' },
    { name: 'agua', type: 'boolean' },
    { name: 'esgoto', type: 'boolean' },
    { name: 'energia', type: 'boolean' },
    { name: 'telefone', type: 'boolean' },
    { name: 'divisas', type: 'boolean' },
    { name: 'calcada', type: 'boolean' },
    { name: 'meio_fio', type: 'boolean' },
    { name: 'galeria', type: 'boolean' },
    { name: 'ilum_publica', type: 'boolean' },
    { name: 'pavimentacao', type: 'boolean' },
    { name: 'educacao', type: 'boolean' },
    { name: 'saude', type: 'boolean' },
    { name: 'coleta_lixo', type: 'boolean' },
    { name: 'limpeza', type: 'boolean' },
    { name: 'nome_vistoriador', type: 'string' }
  ]
})
